// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL é usado pelo CLI do Prisma (migrate), pois pgbouncer não suporta DDL
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
